DjangoTemplates/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('',views.home, name='home'),
    path('my_app/', include('my_app.urls'),name='example'),
    path('admin/', admin.site.urls),
]

my_app/urls.py
from django.urls import path
from . import views

app_name = 'my_app'

urlpatterns = [
    path('',views.example_view, name='example'),
    path('variable/', views.variable_view, name='variable'),
]
 

my_app/models.py
from django.db import models

# Create your models here.

DjangoTemplates/views.py
from audioop import reverse
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse

def home(request):
   #   try:
        return HttpResponseRedirect(reverse('my_app:example'))
   #   except:
   #       return HttpResponse('Unable to redirect')

my_app/views.py
from http.client import HTTPResponse
from django.shortcuts import render
from django.http import HttpResponse

def example_view(request):
    return render(request, 'my_app/example.html')

def variable_view(request):
    
    my_var = {
        'fname':'Hard','lname':'pope',
        'some_list':[1,2,3,4,5,6,7,8],
        'tech':{'front-end':'ReactJs', 'back-end':'Django', 'Database':'MongoDB', 'UI/UX':'AdobeXD'}
    }
    
    return render(request,'my_app/variable.html', context =my_var)

my_app/templates/my_app/example.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Hardpope! Escape this shithole!</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-bar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee {font-size:200px}
</style>
</head>
<body>

<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-red w3-card w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-red" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <a href="#" class="w3-bar-item w3-button w3-padding-large w3-white">Home</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Link 1</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Link 2</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Link 3</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Link 4</a>
  </div>

  <!-- Navbar on small screens -->
  <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
    <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 1</a>
    <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 2</a>
    <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 3</a>
    <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 4</a>
  </div>
</div>

<!-- Header -->
<header class="w3-container w3-red w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-jumbo">HardPope</h1>
  <p class="w3-xlarge">Trying hard to escape the Comfort Zone!</p>
  <a href="{% url 'my_app:variable' %}" class="w3-button w3-black w3-padding-large w3-large w3-margin-top">Get Started</a>
</header>

<!-- First Grid -->
<div class="w3-row-padding w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3-twothird">
      <h1>Lorem Ipsum</h1>
      <h5 class="w3-padding-32">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</h5>

      <p class="w3-text-grey">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint
        occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
        laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>

    <div class="w3-third w3-center">
      <i class="fa fa-anchor w3-padding-64 w3-text-red"></i>
    </div>
  </div>
</div>

<!-- Second Grid -->
<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3-third w3-center">
      <i class="fa fa-coffee w3-padding-64 w3-text-red w3-margin-right"></i>
    </div>

    <div class="w3-twothird">
      <h1>Lorem Ipsum</h1>
      <h5 class="w3-padding-32">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</h5>

      <p class="w3-text-grey">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint
        occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
        laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
  </div>
</div>

<div class="w3-container w3-black w3-center w3-opacity w3-padding-64">
    <h1 class="w3-margin w3-xlarge">Quote of the day: live life</h1>
</div>

<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity">  
  <div class="w3-xlarge w3-padding-32">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
 </div>
 <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>

<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

</body>
</html>

my_app/templates/my_app/variable.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Hardpope: Get outta this shithole!</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
  ul #menu li {
    display:inline;
  }
</style>
</head>


<body class="w3-content" style="max-width:1300px">



<!-- First Grid: Logo & About -->
<div class="w3-row">
  <div class="w3-half w3-black w3-container w3-center" style="height:805px;line-height:1.5;display:inline-block;vertical-align:middle;">
    <div class="w3-padding-75">
      <h1>{{fname | upper}} {{lname | upper}}</h1>
    </div>
    <div class="w3-padding-75 w3-center">
      <a href="{% url 'my_app:example'%}" class="w3-button w3-black w3-block w3-hover-blue-grey w3-padding-16">Home</a>
      <a href="https://www.github.com/ajitrchv" class="w3-button w3-black w3-block w3-hover-teal w3-padding-16">My Work</a>
      <a href="https://www.linkedin.com/in/ajithvreji" class="w3-button w3-black w3-block w3-hover-dark-grey w3-padding-16">Resume</a>
      <a href="https://whatsapp.me/+917907540957" class="w3-button w3-black w3-block w3-hover-brown w3-padding-16">Contact</a>
    </div>
  </div>
  <div class="w3-half w3-blue-grey w3-container" style="height:805px">
    <div class="w3-padding-64 w3-center">
      <h1>About Me</h1>
      <img src="{% static 'my_app/img.png' %}" class="w3-margin w3-circle" alt="Person" style="width:25%">
      <div class="w3-row">
        {% comment %} C:\Users\ajith\Desktop\Notes\Django\DjangoTemplates\my_app\static\my_app\img.png {% endcomment %}
        <div>
          {% for key, value in tech.items%}
        
        
          <div><h1>{{key}}</h1></div>
          <div><p>{{value}}</p></div>
          <hr>
          
            

          {% endfor %}
        </div>

      </div>
    </div>
    
  </div>
</div>



<!-- Footer -->
<footer class="w3-container w3-black w3-padding-16">
  <p></p>
</footer>

</body>
{% comment %} {% endblock 'content'%} {% endcomment %}
</html>